### ISSUE TITLE
questions about image fusion part experiments

### ISSUE THREAD

**Issue by challow0** [bupt-ai-cz/LLVIP#16]
Thanks for your great work ~ I have some questions about the experiments.
I want to know how many images you used in the image fusion part experiment. Did you use all the images for training the FusionGAN and Densefuse algorithm? Or just the images in the directory? And what are the parameters you used?
Looking forward to your reply.

**Comment by ShenXinchang** [comment]
Hi~
We used a subset of LLVIP dataset in all image fusion experiments. The subset has 1000+ image pairs and includes all the scenes in LLVIP dataset. The training parameters for FusionGAN and Densefuse experiments are defult setting.
Due to the impact of Covid-19, we will release the training data and the subset after a short period of time.
Best wishes.

**Comment by challow0** [comment]
@ShenXinchang 
Thanks for your reply. Wish you can release it soon.😄
